DATA:
  data_root: /root/dataset/voc2012/
  train_list: /root/dataset/voc2012/list/train_aug.txt
  val_list: /root/dataset/voc2012/list/val.txt
  classes: 21

TRAIN:
  arch: deeplabv3
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0, 1, 2, 3]
  workers: 16  # data loader workers
  batch_size: 56  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1
  print_freq: 10
  save_freq: 10
  save_path: exp/voc2012/deeplabv3/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

VAL:
  test_list: /root/autodl-tmp/voc2012/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/voc2012/deeplabv3/model/train_epoch_50.pth  # evaluation model path
  save_folder: exp/voc2012/deeplabv3/result/epoch_50/val/ss  # results save folder
  colors_path: data/voc2012/voc2012_colors.txt  # path of dataset colors
  names_path: data/voc2012/voc2012_names.txt  # path of dataset category names

Backdoor:
  dataset: voc2012
  victim_class: 15
  target_class: 0
  trigger_name: hello_kitty
  trigger_path: trigger/hello_kitty.png
  trigger_transparency: 1

TrainBackdoor:
  train_NNI: False 
  train_PRL: False
  train_scale: 1
  train_trigger_size: 15
  train_edge_crop: 100
  train_lower_dist: 0
  train_upper_dist: 0
  train_num_poison: 242
  train_num_perturb: 50000 # Increase the number of perturbation to achieve higher ASR using PRL

TestBackdoor:
  test_scale: 1
  test_trigger_size: 15
  test_edge_crop: 100
  test_lower_dist: 0
  test_upper_dist: 0
  test_num_poison: 446
  test_num_perturb: 50000
  

